### ISSUE TITLE
Protobuf support for 2.4?

### ISSUE THREAD

**Issue by bryanvpham** [logstash-plugins/logstash-codec-protobuf#13]
has the plugin been tested with Logstash 2.4? there no documentation for it, based on debug logs, everything loads properly. I was playing around with logstash-output-stdout in order to test it out. I get no errors and 
```
    @codec.on_event do |event, data|
      puts "meow"
      $stdout.write(data)
    end
```
I never get my "meow" if I'm using "protobuf" codec. The logs say it finds my class file and my class just fine. It just doesn't get encoded or run the code it should once it does.

**Comment by IngaFeick** [comment]
The event api of logstash has changed significantly between versions 2 and 5, so the plugin isn't expected to work with the version 2.x, sorry.
