### ISSUE TITLE
Provide Installation Instructions

### ISSUE THREAD

**Issue by numbnut** [logstash-plugins/logstash-codec-protobuf#2]
Hi there,
I'm unsure about the state of this plugin and how to install it. The instructions seems to be outdated, because they are referencing an old gem, which seems to be not Logstash 5.0 ready. Is this plugin in an experimental state and not released yet? Is there a roadmap about the release date?
Thanks a lot!

**Comment by IngaFeick** [comment]
Hi there! You're right, the current one is not yet logstash 5 ready. We're very much working on that right now. I'll let you know when it's finished and provide some updated installation instructions.

**Comment by numbnut** [comment]
Thank you very much for the fast response. Could you give a rough estimation of how long it will take? Is it a month or a year? Just curios about it.

**Comment by IngaFeick** [comment]
Let me come back at you next week, then I should be able to estimate this better. Definitely not a year ;)
Cheers!

**Comment by numbnut** [comment]
Sounds great! Thank you very much and take your time. I don't want to hustle you.

**Comment by IngaFeick** [comment]
Hey there, good news: you can now install the plugin via the normal command:
    bin/logstash-plugin install logstash-codec-protobuf
Let me know if you run into any issues, happy to help!

**Comment by numbnut** [comment]
Thank you very much. I will let you know, if anything goes wrong.
