### ISSUE TITLE
Unexpected EOF error occured while decoding protobuf message from kafka

### ISSUE THREAD

**Issue by hooom** [logstash-plugins/logstash-codec-protobuf#22]
backgroud: logstash-codec-protobuf plugin produces proto messages and output to kafka. Another plugin consumes kafka data and decodes proto message. But some message parse failed.

error info : com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.

proto message: message type fields are all string types.

Test results: proto message whoes original string field length is less than or equal to 127 bits can be successfully parsed, while those that exceed 127 bits can be parsed unsuccessfully.

who can help me analyze the error?  
Thanks

**Comment by IngaFeick** [comment]
Hi there,
could you please provide the protobuf definition, the logstash config and one or two sample messages that trigger this error message (if possible)? Thank you!

**Comment by IngaFeick** [comment]
What does your logstash config look like, please?

**Comment by IngaFeick** [comment]
Closing this due to insufficient information.
