### ISSUE TITLE
Document class_name in version 3

### ISSUE THREAD

**Issue by dtheodor** [logstash-plugins/logstash-codec-protobuf#24]
It took me forever to debug why I was getting `The given configuration is invalid. Reason: undefined method 'msgclass' for nil:NilClass` errors.

The class_name when using proto 3 should be the string value that the google library uses to register the object in the descriptor pool, e.g. by calling `add_message "animals.Cow"`. This is the same string used in the bottom of the generated file to lookup the object `Google::Protobuf::DescriptorPool.generated_pool.lookup("animals.Cow")`

It is not a name of a module/class that appears anywhere in the file, it is the registered string value.

**Comment by IngaFeick** [comment]
Hi @dtheodor, thanks for the info. I will point that out in the README.

**Comment by corsc** [comment]
Sorry, I am facing this issue as well but my generated `.pb.rb` file has no `add_message` calls at the bottom.
Any ideas?
