### ISSUE TITLE
Possible doco extension

### ISSUE THREAD

**Issue by corsc** [logstash-plugins/logstash-codec-protobuf#26]
I am writing from Go to Kafka.

I was getting error messages like:
`Couldn't decode protobuf: #<RuntimeError: CodedInputStream encountered a malformed varint.>.`
And:
`Couldn't decode protobuf: #<RuntimeError: Protocol message end-group tag did not match expected tag.>.`
And even incorrect data sometimes.  My int64 was coming through with the wrong value.

Turns out the issue not setting the serializers to the appropriate values.
In my case it was:
```
input {
	kafka {
		key_deserializer_class => "org.apache.kafka.common.serialization.ByteArrayDeserializer"
		value_deserializer_class => "org.apache.kafka.common.serialization.ByteArrayDeserializer"
	}
}
```

Perhaps someone more knowledgeable then I could add some comments to the documentation to help newbies like me?
Cheers

**Comment by IngaFeick** [comment]
Thank you, Corey, much appreciated! I will add that. Cheers!

**Comment by corsc** [comment]
No worries and definitely no need to apologise.  Thanks again
