### ISSUE TITLE
how does the this plugin deal with sticky packet when use it in tcp input ?

### ISSUE THREAD

**Issue by Xztty** [logstash-plugins/logstash-codec-protobuf#27]
https://github.com/logstash-plugins/logstash-codec-protobuf/blob/bd970347048932f8f39ca7addb4db91462593bdb/lib/logstash/codecs/protobuf.rb#L77

I am newbie in Ruby. From the code above,  it seems like it didn't deal with sticky packet. It just decode the data from logstash-core with protobuf decoder. ( I print out the type of data, it is `String`) But the data may be part of one protobuf message or a sticky packet with many protobuf message

I write a tool that send raw data that is encoded with protobuf. When I send one message alone, the plugin work well. 
`packet1_raw_data`
But when I duplicate the raw data twice, the plugin cannot decode two event. 
`packet1_raw_data packet1_raw_data`

Is this a bug for the plugin?

 And I need to write a codec that similar with logstash-codec-protobuf.

It's test with: 
logstash-6.0.1
logstash-codec-protobuf (1.0.3)

**Comment by IngaFeick** [comment]
Hi, 
would you mind providing a full failing test, such as the tool that you use to produce said data? Thank you.

**Comment by Xztty** [comment]
I have commit the code here  https://github.com/Xztty/pytools

You can reproduce the result like this.

- use test logstash `test/test_codec_logstash.conf` and put `n.pb.rb` in the write place. and then start logstash with this config
- run command like this, the test_rawdata.txt have two protobuf massage duplicated
`python send_bytes.py test/test_rawdata.txt 127.0.0.1 5999`
- from the logstash output, there is only one event

```
{
    "@timestamp" => 2018-07-03T15:12:06.117Z,
          "port" => 38944,
     "@metadata" => {
        "type" => "protobuf-zhiyun"
    },
      "@version" => "1",
          "host" => "pcmgr1",
      "real_pkg" => "a",
      "@metdata" => {
        "ip_address" => "10.222.144.26"
    },
      "pkg_type" => 20
}
```

**Comment by IngaFeick** [comment]
Thanks @Xztty. Are you sure this is an issue with the codec, though? Asking for two reasons: 
a) it is the input plugin's responsibility to receive the incoming data and cut them into appropriate pieces. The codec's responsibility is to transform said pieces from format a to a desired format b. If the data is not being dissected correctly in the first place then this would fall into the domain of the input plugin.
b) I'm not sure this is even supposed to work. The [tcp input plugin documentation](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html) states that 
`Like stdin and file inputs, each event is assumed to be one line of text.`. If you put two events into one line, like [you do](https://github.com/Xztty/pytools/blob/master/send_bytes.py#L77) then it will not work. If you messages spreading over multiple lines, it will probably not work either.

**Comment by Xztty** [comment]
from [codec](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html#plugins-inputs-tcp-codec) 
`The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.`

**Comment by flying1020** [comment]
The issue is logstash send every event without any separator whe use tcp output plugin.
Tcp server cannot split events which reveiced.
How can i specified a special separator just like '\n' or '\r'?

**Comment by jorgelbg** [comment]
We've created issue #58 to track this feature as this has been mentioned a couple of times already.
