### ISSUE TITLE
Logstash uses protobuf, running error: NoMethodError”, :message=>”undefined method `msgclass’ for nil:NilClass”

### ISSUE THREAD

**Issue by sunchanglong1991** [logstash-plugins/logstash-codec-protobuf#29]
I use google protobuf in the logstash input,Start error when running logstash。

Logstash version is 6.3.0, protoc version is 3.6.1, ruby-protoc version is 1.6.1, Elk community question connection is as follows： https://discuss.elastic.co/t/logstash-uses-protobuf-running-error-nomethoderror-message-undefined-method-msgclass-for-nil-nilclass/144806?u=sun_changlong

Is it my environmental factor or the protobuf version? Can be used in the protobuf 2 environment.Welcome to leave valuable suggestions

the  error is:
> [ERROR][logstash.agent ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exceptio n=>"NoMethodError", :message=>"undefined method msgclass' for nil:NilClass", :backtrace=>["/home/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-pr otobuf-1.1.0/lib/logstash/codecs/protobuf.rb:101:inregister'", "/home/logstash/logstash-core/lib/logstash/codecs/base.rb:20:in initialize'", "/home/logs tash/logstash-core/lib/logstash/plugins/plugin_factory.rb:97:inplugin'", "/home/logstash/logstash-core/lib/logstash/pipeline.rb:110:in plugin'", "(eval) :8:in'", "org/jruby/RubyKernel.java:994:in eval'", "/home/logstash/logstash-core/lib/logstash/pipeline.rb:82:ininitialize'", "/home/logstash/log stash-core/lib/logstash/pipeline.rb:167:in initialize'", "/home/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:40:inexecute'", "/home/log stash/logstash-core/lib/logstash/agent.rb:305:in `block in converge_state'"]}

the 'register' in the 'logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-protobuf-1.1.0/lib/logstash/codecs/protobuf.rb' is:
```
def register
  @metainfo_messageclasses = {}
  @metainfo_enumclasses = {}
  @metainfo_pb2_enumlist = []
  include_path.each { |path| load_protobuf_definition(path) }
  if @protobuf_version == 3
    @pb_builder = Google::Protobuf::DescriptorPool.generated_pool.lookup(class_name).msgclass
  else
    @pb_builder = pb2_create_instance(class_name)
  end
end
```

**Comment by willbuckner** [comment]
I am having this same issue as well.

**Comment by IngaFeick** [comment]
Hi @willbuckner  and @sunchanglong1991 , could you please provide your logstash configs, at least the input section, and the protobuf definitions that you are referencing? Thank you.

**Comment by IngaFeick** [comment]
@sunchanglong1991  could you please try to change the following in your logstash config:

Instead of 
`class_name => ["Elk.ElkData"]`
try
`class_name => ["elk.ElkData"]`
? 

Thank you and sorry for the late reply.

**Comment by marcosflobo** [comment]
Hi all,

Any resolution on this?

Thanks

**Comment by IngaFeick** [comment]
@marcosflobo To me it looks like a configuration error. Can you provide your logstash config and protobuf classes? Happy to have a look. Thanks :)

**Comment by rahulkumar-pawar** [comment]
if `elk ` is the package name in your .proto it might get initialized. Faced the same issue and by removing package name and compiled it then provide only class name referred from compiled _pb.rb file. This helps me to solve the issue.
One more thing you have to compile .proto with Google official compiler 3.5.0.

Still looking into it, why it is throwing an error if the package name is part of .proto

**Comment by IngaFeick** [comment]
@marcosflobo thanks a lot for the feedback!
