### ISSUE TITLE
the doc is out of date

### ISSUE THREAD

**Issue by lecoan** [logstash-plugins/logstash-codec-protobuf#35]
Hey, I found the doc in https://www.elastic.co/guide/en/logstash/current/plugins-codecs-protobuf.html is out of date and could be really misleading if someone use protobuffer3. 
this doc is written for user who use version 2 but doesn't indicate this, which takes me lots of time to figure it out why logstash keep send me warning

**Comment by IngaFeick** [comment]
Thanks a lot @lecoan !

**Comment by IngaFeick** [comment]
Update to documentation has been merged.
