### ISSUE TITLE
DecodeError of juniper telemetry port.proto

### ISSUE THREAD

**Issue by jendamozna** [logstash-plugins/logstash-codec-protobuf#37]
Hello
im getting error when trying to parse juniper telemetry data

logstash 6.6.1
logstash-codec-protobuf (1.1.0)
libprotoc 3.7.0
ruby-protoc 1.6.1

```
[2019-03-14T10:15:31,162][WARN ][logstash.codecs.protobuf ] Couldn't decode protobuf: #<ProtocolBuffers::DecodeError: incorrect wire type for tag: 5, expected 2 but got 0
#<ProtocolBuffers::Field::MessageField:0x16492e41 @otype=:repeated, @name=:egress_queue_info, @opts={}, @tag=5, @proxy_class=QueueStats>>.
```

logstash config:
```
input {
    udp {
      port => 15443
      type => "junos-proto"
      codec => protobuf {
        class_name => "InterfaceInfos"
        include_path => ['/etc/logstash/pb_definitions/18/port.pb.rb']
      }
    }
}
output {
    stdout {codec => rubydebug { metadata => true }}
}
```

I can succesfully read data this way:
```
$ nc -ul 0.0.0.0 15443 > data.gpb
$ protoc --decode=TelemetryStream ./port.proto -I . < data.gpb > protoc.decode.txt
```
protoc.decode.txt
https://pastebin.com/30upp1ep

protoc.decode_raw.txt
https://pastebin.com/pcJYAvpf

port.proto
https://pastebin.com/RZt7CgRt

port.pb.rb
https://pastebin.com/80TedwDq

telemetry_top.proto
https://pastebin.com/B525rtrd

Any idea what could be wrong? Is my logstash config OK? Should i include also telemetry_top.pb.rb? Or change class_name?

**Comment by IngaFeick** [comment]
Hi. Yes, you need to include the telemetry_top file aswell, before you include the other one. The class name looks okay.

**Comment by jendamozna** [comment]
here are some tests... no success still

```
class_name => "TelemetryStream"
include_path => ['/etc/logstash/pb_definitions/18/telemetry_top.pb.rb','/etc/logstash/pb_definitions/18/port.pb.rb']
{
    "sequence_number" => 474079,
      "version_minor" => 1,
       "component_id" => 0,
         "@timestamp" => 2019-03-14T08:24:26.221Z,
          "system_id" => "hostname-MX960-01:10.asdfasdf",
         "enterprise" => {},
           "@version" => "1",
               "host" => "192.ip.add.ress",
               "type" => "junos-proto",
      "version_major" => 1,
        "sensor_name" => "test-13:/junos/system/linecard/interface/:/junos/system/linecard/interface/:PFE",
          "timestamp" => 1552552147339
}
```

```
class_name => "EnterpriseSensors"
include_path => ['/etc/logstash/pb_definitions/18/telemetry_top.pb.rb','/etc/logstash/pb_definitions/18/port.pb.rb']
{
    "@timestamp" => 2019-03-14T08:26:31.214Z,
          "host" => "192.ip.add.ress",
      "@version" => "1",
          "type" => "junos-proto"
}
```

```
class_name => "JuniperNetworksSensors"
include_path => ['/etc/logstash/pb_definitions/18/telemetry_top.pb.rb','/etc/logstash/pb_definitions/18/port.pb.rb']
{
    "@timestamp" => 2019-03-14T08:30:03.186Z,
          "host" => "192.ip.add.ress",
      "@version" => "1",
          "type" => "junos-proto"
}
```

```
class_name => "Port"
include_path => ['/etc/logstash/pb_definitions/18/telemetry_top.pb.rb','/etc/logstash/pb_definitions/18/port.pb.rb']
[2019-03-14T10:28:03,194][WARN ][logstash.codecs.protobuf ] Couldn't decode protobuf: #<ProtocolBuffers::DecodeError: invalid message>.
```


```
class_name => "InterfaceStats"
include_path => ['/etc/logstash/pb_definitions/18/telemetry_top.pb.rb','/etc/logstash/pb_definitions/18/port.pb.rb']
[2019-03-14T10:34:56,252][WARN ][logstash.codecs.protobuf ] Couldn't decode protobuf: #<ProtocolBuffers::DecodeError: incorrect wire type for tag: 1, expected 0 but got 2
#<ProtocolBuffers::Field::Uint64Field:0x1b56cafe @otype=:optional, @name=:if_pkts, @opts={}, @tag=1>>.
```

I expect i could iterate over interfaces... using json/split...

**Comment by mohsin106** [comment]
Hi @jendamozna, I'm trying to collect telemetry data from a Juniper PTX10K using Juniper's native sensor model. Do you have any documentation I can read that will help me accomplish this using Logstash? I understand I'm going to need to generate Google proto buff files from the router and then specify those files in my Logstash conf file. I'm currently able to collect OpenConfig sensor data using Telegraf's JTI plugin, but I would like to be able to collect Juniper Native Sensor data which Telegraf does not support. I appreciate any help/guidance you can provide. Thank you.

**Comment by jendamozna** [comment]
Hi @mohsin106, i wasn't able to do that via logstash, i've solved it with some fluent/juniper/telegraf plugin. I was working only with InterfaceStats protobuf.

**Comment by mohsin106** [comment]
@jendamozna , ok cool thanks.

**Comment by 3fr61n** [comment]
Hi Guys.

It would be nice, to understand why the 'enterprise' nested hierarchy is not being decoded by this plugin.  

Because using protoc tool it decodes the whole hierarchy using the same .proto files.  (I used this instructions https://www.juniper.net/documentation/en_US/junos/topics/reference/general/junos-telemetry-interface-decoding-data.html)

```
juniper@host:~/junos-telemetry-interface$ protoc --decode TelemetryStream svcset_telemetry.proto -I . < data.gpb 
system_id: "ms00:172.16.254.2"
component_id: 0
sub_component_id: 0
sensor_name: "ipsec:/junos/services/spu/ipsec-vpn/:/junos/services/spu/ipsec-vpn/:SERVICEPIC"
sequence_number: 720
timestamp: 1615409078876
version_major: 1
version_minor: 0
enterprise {
  [juniperNetworks] {
    [jnprScvsInfraExt] {
      svcs_plugins_info {
        sp_num_plugins: 20
        sp_name: "junos-stateful-firewall"
```

**Comment by jsandbrook** [comment]
Just leaving a breadcrumb. I encountered this exact issue and struggled mightily finding any related discussions about it beyond this issue.

This plugin relies on ruby-protocol-buffers which does not support extensions (https://github.com/codekitchen/ruby-protocol-buffers/#currently-unsupported-features). Parsing extended messages succeeds while silently dropping that data.

All useful Juniper telemetry data is hidden behind extensions within the enterprise field. Unless ruby-protocol-buffers starts supporting them, this plugin can't be used to directly ingest Juniper telemetry protobufs.
