### ISSUE TITLE
Tried to load a plugin's code, but failed

### ISSUE THREAD

**Issue by duculete** [logstash-plugins/logstash-codec-protobuf#49]
I get this error when I am using this plugin with logstash 7.4.2

Tried to load a plugin's code, but failed. {:exception=>#<LoadError: no such file to load -- logstash/codecs/protobuf>, :path=>"logstash/codecs/protobuf", :type=>"codec", :name=>"protobuf"}

[ERROR][logstash.plugins.registry] Tried to load a plugin's code, but failed. {:exception=>#<LoadError: no such file to load -- logstash/codecs/protobuf>, :path=>"logstash/codecs/protobuf", :type=>"codec", :name=>"protobuf"}
Dec 19 16:10:39 clrv0000172125.ic.ing.net logstash[36584]: [2019-12-19T16:10:39,687][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:kafka2file_proto, :exception=>"Java::JavaLang::IllegalStateException", :message=>"Unable to configure plugins: (PluginLoadingError) Couldn't find any codec plugin named 'protobuf'. Are you sure this is correct? Trying to load the protobuf codec plugin resulted in this error: no such file to load -- logstash/codecs/protobuf", :backtrace=>["org.logstash.config.ir.CompiledPipeline.<init>(CompiledPipeline.java:100)", "org.logstash.execution.JavaBasePipelineExt.initialize(JavaBasePipelineExt.java:60)", "org.logstash.executi
.....

**Comment by IngaFeick** [comment]
Hey, can you please run `bin/logstash-plugin list --verbose | grep -i proto` and report the outcome?

**Comment by duculete** [comment]
Hello,

bin/logstash-plugin list --verbose | grep -i proto
logstash-codec-protobuf (1.2.2)

**Comment by IngaFeick** [comment]
Would you mind posting your full configuration? Thanks

**Comment by duculete** [comment]
Fixed, some permissions problem.

**Comment by ravitandur** [comment]
I am also facing similar issue. Can you please let me know how did you resolve this issue? Thank yo in advance.
