### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by sgarap** [logstash-plugins/logstash-codec-protobuf#5]
Hi,
I tried to install logstash-codec-protobuf plgin to logstash 5.2
There is a proxy  configured on the server to access Internet. rubygems.org is accessible from the machine, but logstash-codec-protobuf plugin is not installed. It prints Validating logstash-code-protobuf, but doesn't do any thing even after 20 minutes. See below. I used RHEL 1.3 as OS Kernel version: 3.10.0-327.36.1.el7.x86_64

curl -v -L rubygems.org
 HTTP/1.1 200 Connection established
**./logstash-plugin install logstash-codec-protobuf --verbose
Validating logstash-codec-protobuf**

After nearly an hour it printed following error
Installing logstash-codec-protobuf
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.2.0), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.2.0'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported

I tried to install the gem it is complaining and it returned
 gem install logstash-core-event-java -v '5.2.0'
ERROR:  Could not find a valid gem 'logstash-core-event-java' (= 5.2.0), here is why:
          Found logstash-core-event-java (5.2.0), but was for platform java
ERROR:  Possible alternatives: logstash-core-event, logstash-codec-nmap, logstash-event, logstash-codec-netflow, logstash-codec-frame

**Comment by IngaFeick** [comment]
Heyho!
The codec has become a part of the official plugins and can easily be installed by running 
`bin/logstash-plugin install logstash-codec-protobuf`
I will update the documentation. Thanks for letting me know! Please tell me if you run into any problem with the aforementioned command.

**Comment by sgarap** [comment]
@IngaFeick

**Comment by IngaFeick** [comment]
@sgarap which version of logstash are you using exactly? 5.2.x?

**Comment by sgarap** [comment]
@IngaFeick 
./logstash --version
logstash 5.2.0

**Comment by IngaFeick** [comment]
Thanks @sgarap. I just downloaded a vanilla logstash and tested the command, seems to be working fine: 
`~/Downloads/logstash-5.2.0
❯ bin/logstash-plugin install logstash-codec-protobuf
Validating logstash-codec-protobuf
Installing logstash-codec-protobuf
Installation successful`

Would you mind trying if the same problem happens for any other plugin? Maybe just install some random plugin like `bin/logstash-plugin install logstash-codec-avro` to see if the problem is related to the protobuf codec or not?

**Comment by sgarap** [comment]
@IngaFeick There seems to be some problem with invoking proxy  from logstash side. I downloaded 5.4.0 on windows machine and installation worked fine over there.

**Comment by IngaFeick** [comment]
@sgarap I was suspecting an issue with your internet connectivity. Maybe run a netstat or something to see what it's trying to connect to and check if that is reachable through your proxy? I'm not familiar with the internals of the installation process so I'd have to run a test aswell.

**Comment by sgarap** [comment]
Worked on windows. Used offline plugin management to install it on linux offline servers.
