### ISSUE TITLE
Map Values from proto are  misplaced after decoding in logstash

### ISSUE THREAD

**Issue by sgarap** [logstash-plugins/logstash-codec-protobuf#8]
Hi I generated the following .pb.rb file from .proto using https://github.com/codekitchen/ruby-protocol-buffers
`#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Httpendpoint
  # forward declarations
  class Payload < ::ProtocolBuffers::Message; end

  class Payload < ::ProtocolBuffers::Message
    # forward declarations
    class CustomFieldsEntry < ::ProtocolBuffers::Message; end

    set_fully_qualified_name "httpendpoint.Payload"

    # nested messages
    class CustomFieldsEntry < ::ProtocolBuffers::Message
      set_fully_qualified_name "httpendpoint.Payload.CustomFieldsEntry"

      optional :string, :key, 1
      optional :string, :value, 2
    end

    optional :string, :version, 1
    optional :string, :host, 2
    optional :string, :shortMessage, 3
    optional :string, :fullMessage, 4
    optional :int64, :timestamp, 5
    optional :int32, :level, 6
    repeated ::Httpendpoint::Payload::CustomFieldsEntry, :customFields, 7
  end

end
`
I sent an input message (protobuf.tostring representation) to kafka as follows.
Payload:version: "1.1"
host: "unknown"
shortMessage: "Gelf validation error: timestamp is not valid"
fullMessage: "\"Original Json: {\"_some_info\":\"foo\",\"short_message\":\"A short message to test the index\",\"full_message\":\"112.169.19.192 - - [10/Oct/2016:10:18:30 0900] GET \\\"/ HTTP/1.1 200 44346 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.152 Safari/537.22\\\"\",\"level\":1,\"host\":\"example.org\",\"_some_env_var\":\"bar\",\"_user_id\":9001,\"version\":\"1.1\",\"timestamp\":1496331385000}\""
level: 1
customFields {
  key: "_successfully_parsed"
  value: "false"
}
customFields {
  key: "_id"
  value: "xyz"
}
customFields {
  key: "_authenticated"
  value: "true"
}

In logstash as part of kafka input I defined
codec => protobuf
        {
          class_name => "Httpendpoint::Payload"
          include_path => ['/usr/bin/logmessage.pb.rb']
        }

Using stdout { codec => rubydebug}, I saw that the messae recieved is as follows. The custom fields are added to field full_message and customFields are empty. Is something wrong here with the code configuration?

15:52:11.761 [[main]>worker0] DEBUG logstash.pipeline - output received {"event"=>{"@timestamp"=>2017-06-01T15:52:11.747Z, "**customFields"=>[]**, "host"=>"unknown", "shortMessage"=>"Gelf validation error: timestamp is not valid", "@version"=>"1", "fullMessage"=>"\"Original Json: {\"_some_info\":\"foo\",\"short_message\":\"A short message to test the index\",\"full_message\":\"112.169.19.192 - - [10/Oct/2016:10:18:30 0900] GET \\\"/ HTTP/1.1 200 44346 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.152 Safari/537.22\\\"\",\"level\":1,\"host\":\"example.org\",\"_some_env_var\":\"bar\",\"_user_id\":9001,\"version\":\"1.1\",\"timestamp\":1496331385000}\"0\u0001:\u001D\n\u0014**_successfully_parsed\u0012\u0005false:\u0014\n\t_id\u0012\axyz:\u0016\n\u000E_authenticated\u0012\u0004true**", "version"=>"1.1"}}
{
      "@timestamp" => 2017-06-01T15:52:11.747Z,
    **"customFields" => [],**
            "host" => "unknown",
    "shortMessage" => "Gelf validation error: timestamp is not valid",
        "@version" => "1",
     "fullMessage" => "\"Original Json: {\"_some_info\":\"foo\",\"short_message\":\"A short message to test the index\",\"full_message\":\"112.169.19.192 - - [10/Oct/2016:10:18:30 0900] GET \\\"/ HTTP/1.1 200 44346 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.152 Safari/537.22\\\"\",\"level\":1,\"host\":\"example.org\",\"_some_env_var\":\"bar\",\"_user_id\":9001,\"version\":\"1.1\",\"timestamp\":1496331385000}\"0\u0001:\u001D\n\u0014_**successfully_parsed\u0012\u0005false:\u0014\n\t_id\u0012\axyz:\u0016\n\u000E_authenticated\u0012\u0004true**",
         "version" => "1.1"
}

**Comment by IngaFeick** [comment]
Hi @sgarap , 
sorry for the delay! Would you mind providing the version of the protobuf codec that you are using? You can get it by running `bin/logstash-plugin list --verbose | grep protobuf`
Thank you

**Comment by IngaFeick** [comment]
@sgarap is this issue still ongoing for you?

**Comment by sgarap** [comment]
@IngaFeick We are now converting the protobuf to json before writing the data to elasticsearch. We don't use this plugin anymore.
